from flask import Flask, render_template, request, jsonify
import random
import re

app = Flask(__name__)

# Define your chatbot patterns and responses
patterns = [
   (r'hello|hi|hey|jambo|hujambo', ['Hello!', 'Hi there!', 'Hey!', 'Jambo!', 'Sasa!']),
    (r'how are you?|how are you doing?|habari ya asubuhi', ['I am doing well, thank you!', 'Niko poa, asante. Habari yako?', 'Nzuri sana, shukrani!']),
    (r'help|nisaidie|saidia', ['Sure, I can help you with financial and student-related questions. Just ask!', 'Bila shaka, naweza kusaidia na maswali kuhusu masomo na mambo ya fedha. Uliza tu!']),
    (r'create a budget|fanya bajeti', ['To create a budget as a campus student, start by listing your monthly income and expenses. Be sure to include tuition fees, rent, groceries, transportation, and any other essential expenses. Allocate a portion of your income for savings and prioritize essential expenses. Consider using budgeting apps or spreadsheets to track your spending and adjust your budget as needed.']),
    (r'saving money|hifadhi pesa', ['As a campus student, saving money is important for financial security. Try to save a portion of your income regularly, even if it\'s a small amount. Consider setting up automatic transfers to a savings account to make saving easier. Look for ways to cut costs, such as cooking at home instead of eating out or buying used textbooks instead of new ones.']),
    (r'student loans|mikopo ya wanafunzi', ['Student loans are a common way to finance higher education. Be sure to understand the terms and conditions of any loans you take out, including interest rates and repayment options. Consider applying for scholarships or grants to reduce the need for loans. If you do take out loans, borrow only what you need and explore options for federal loans with favorable repayment terms.']),
    (r'part-time job|kazi ya muda|kazi ya vibarua', ['Working part-time can be a great way to earn extra money as a campus student. Look for job opportunities on campus or in your local community that fit your schedule and interests. Common part-time jobs for students include working in retail, food service, tutoring, or as a campus tour guide. Be sure to prioritize your studies and choose a job that allows you to balance work and academics effectively.']),
    (r'food preparation|maandalizi ya chakula', ['If you enjoy cooking, consider offering food preparation services to other students. You could prepare healthy meals or snacks and sell them on campus or through social media. Be sure to check local regulations and obtain any necessary permits before starting a food business. You could also offer meal prep workshops or cooking classes for other students.']),
    (r'instagram thrift shops|maduka ya pili ya instagram', ['Instagram thrift shops are a popular way to buy and sell secondhand clothing and accessories. If you have an eye for fashion and enjoy curating outfits, consider starting your own Instagram thrift shop. You can source clothing from thrift stores, garage sales, or your own closet and sell them to your followers. Be sure to take high-quality photos and provide accurate descriptions of the items you\'re selling.']),
    (r'tiktok influencer|tiktok influencer', ['Becoming a TikTok influencer can be a fun way to earn money and build a personal brand. To become a successful influencer, focus on creating engaging and original content that resonates with your audience. Choose a niche or topic that you\'re passionate about and consistently post high-quality videos. Engage with your followers and collaborate with other creators to grow your audience. Once you have a large following, you can monetize your TikTok account through sponsored content, brand partnerships, and affiliate marketing.']),
    (r'financial aid|misamaha ya kifedha|msaada wa kifedha', ['Financial aid includes grants, scholarships, loans, and work-study programs that help students pay for college or university. To apply for financial aid, complete the Free Application for Federal Student Aid (FAFSA) and explore other sources of aid offered by your school, state, or private organizations. Financial aid can help cover tuition, fees, books, and living expenses, making higher education more affordable for students.']),
    (r'risk|hatari', ['Risk refers to the potential for loss or harm that may result from uncertain events or circumstances. In finance, risk is often associated with investments and involves the possibility of losing money or not achieving expected returns. Investors assess risk based on factors such as volatility, market conditions, and economic trends. It\'s important to understand and manage risk when making investment decisions to protect your financial assets and achieve your goals.']),
    (r'financial dating advice|ushauri wa kimapenzi wa kifedha', ['When it comes to dating as a campus student, it\'s important to be mindful of your finances and prioritize your financial goals. Be honest with your partner about your financial situation and expectations, and have open discussions about money management and shared expenses. Set boundaries and establish mutual financial goals to avoid conflicts and misunderstandings. Consider low-cost or free date ideas, such as picnics in the park or movie nights at home, to save money while still enjoying quality time together. Remember that financial compatibility is an important aspect of a healthy relationship, so choose partners who respect your financial values and goals.']),
    (r'bye|goodbye|kwa heri|kwa sasa', ['Kwaheri!', 'Tuonane baadaye!', 'Jiweke salama!']),
    (r'(thank you|thanks)|asante', ['Karibu!', 'Nimefurahi kuweza kusaidia!', 'Usiku mwema!']),
    (r'(good morning|good afternoon|good evening)|habari za asubuhi|habari za mchana|habari za jioni', ['Habari za asubuhi!', 'Habari za mchana!', 'Habari za jioni!']),
    (r'(what\'s your name|who are you)|jina lako ni nani|wewe ni nani', ['Mimi ni msaidizi wako wa masomo na fedha!', 'Unaweza kuniita FinStuBot!']),
    (r'(tell me a joke|make me laugh)|nambia chiste|nifurahishe', ['Kwa nini mwanafunzi alileta ngazi shuleni? Kwa sababu alidhani shule ilikuwa bora katika uwanja wake!', 'Kwa nini wanasayansi hawana imani kwa atomi? Kwa sababu wao ni kila kitu!']),
    (r'how to deal with stress and avoid burnout|tips for managing stress|msongo wa mawazo', ['Dealing with stress and avoiding burnout as a student requires self-care and effective time management. Make sure to prioritize your tasks, take regular breaks, exercise, get enough sleep, and seek support from friends, family, or counselors if needed.']),
    (r'finding affordable housing|where to find cheap housing|makazi ya bei nafuu', ['Finding affordable housing as a student can be challenging, but there are options available. Consider living in shared accommodation, off-campus housing, or student dormitories. Look for rental listings on university notice boards, online platforms, or community bulletin boards. You can also reach out to your university\'s housing office for assistance and resources.']),
    (r'how to build credit as a student|establishing credit history|ujengee historia ya mkopo', ['Building credit as a student is important for your financial future. You can start by applying for a student credit card or becoming an authorized user on a parent\'s credit card. Make small purchases and pay your bills on time to establish a positive credit history.']),
    (r'effective study techniques|tips for studying efficiently|njia bora za kusoma', ['To study efficiently, create a study schedule, break your study sessions into manageable chunks, use active learning techniques such as summarizing, teaching others, and practicing retrieval, eliminate distractions, and take regular breaks to avoid burnout.']),
    (r'how to network and build connections|making friends in college|jenga mtandao na ujenge mahusiano', ['Networking and building connections in college is essential for personal and professional growth. Attend campus events, join student clubs and organizations, participate in group study sessions, and reach out to professors and classmates for networking opportunities. Be proactive, genuine, and open-minded in your interactions.']),
    (r'importance of internships|benefits of doing internships|umuhimu wa kufanya mazoezi ya vitendo', ['Internships provide valuable real-world experience, networking opportunities, skill development, and insight into potential career paths. They can help you explore your interests, build your resume, and increase your chances of securing a job after graduation.']),
    (r'how to start a small business|entrepreneurship tips|anzisha biashara ndogo', ['Starting a small business as a student requires careful planning, research, and dedication. Identify a niche or market demand, develop a business plan, secure funding or investment, choose a business structure, register your business, and promote your products or services through marketing and networking.']),
    (r'balancing academics and extracurricular activities|how to manage school and activities|usawa wa masomo na shughuli za ziada', ['Balancing academics and extracurricular activities is crucial for academic success and personal growth. Prioritize your commitments, manage your time effectively, set realistic goals, seek support from professors and advisors, and practice self-care to avoid burnout.']),
    (r'how to negotiate scholarships or financial aid|tips for getting more aid|majadiliano ya misamaha au msaada wa kifedha', ['Negotiating scholarships or financial aid can be intimidating but is worth pursuing. Research scholarship opportunities, highlight your achievements and financial need in your application, write a compelling essay or personal statement, and follow up with the scholarship or financial aid office to inquire about additional funding opportunities or negotiate your award.']),
    (r'career exploration and planning|how to choose a major|utafiti na mipango ya kazi', ['Exploring careers and planning your future requires self-reflection, research, and guidance. Assess your interests, values, skills, and goals, research different career options and industries, seek advice from career counselors, professionals, and alumni, gain relevant experience through internships or part-time jobs, and create a career action plan with short and long-term goals.']),
    (r'how to manage student loans responsibly|repayment strategies|usimamizi wa mikopo ya wanafunzi', ['Managing student loans responsibly is essential to avoid financial hardship and debt. Understand your loan terms and repayment options, create a budget, prioritize loan payments, consider loan consolidation or refinancing, explore income-driven repayment plans or loan forgiveness programs, and communicate with your loan servicer if you encounter financial difficulties.']),
    (r'importance of mental health awareness|self-care tips|umuhimu wa ufahamu wa afya ya akili', ['Mental health awareness and self-care are crucial for your overall well-being and academic success. Practice self-care activities such as exercise, meditation, hobbies, and relaxation techniques, seek support from friends, family, or counselors, prioritize sleep and nutrition, set boundaries, and seek professional help if needed.']),
    (r'how to start investing as a student|investment options for beginners|anzisha uwekezaji kama mwanafunzi', ['Starting to invest as a student can set you up for financial success in the future. Learn about different investment options such as stocks, bonds, mutual funds, and retirement accounts, start small with low-risk investments, diversify your portfolio, research investment strategies, and seek advice from financial professionals or mentors.']),
    
]

def respond(input_text):
    for pattern, responses in patterns:
        if re.match(pattern, input_text, re.IGNORECASE):
            return random.choice(responses)
    return "I'm sorry, I didn't understand. Can you please rephrase or ask a different question?"

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/chat', methods=['POST'])
def chat():
    user_message = request.json.get('message')
    bot_response = respond(user_message)
    return jsonify({'response': bot_response})

if __name__ == '__main__':
    app.run(debug=True)
